---
# Configure mountiso

- name: service is enabled and started
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  become: true
  loop: "{{ mountiso_services_enable }}"
  when: mountiso_enable_service
